ansible_user: admin
ansible_password: Pa$$w0rd
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore

local_users:
  - { name: 'Bala', groups: ['Bala_groups'], password: 'testpassw0rd' }
  - { name: 'Stephen', groups: ['Stephen_groups'], password: 'testpassw0rd' }
  - { name: 'Prakash', groups: ['Prakash_groups'], password: 'testpassw0rd' }
local_groups:
  - Bala_groups
  - Stephen_groups
  - Prakash_groups

